### ISSUE TITLE
Cannot find module 'babel-polyfill'

### ISSUE THREAD

**Issue by antoniovazquezblanco** [particle-iot/particle-cli#415]
In Windows:
```
>npm install -g particle-cli
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN tar EPERM: operation not permitted, open 'C:\Users\avazquezb\AppData\Roaming\npm\node_modules\.staging\form-data-4045fdc8\.npmignore'
C:\Users\avazquezb\AppData\Roaming\npm\particle -> C:\Users\avazquezb\AppData\Roaming\npm\node_modules\particle-cli\bin\particle.js
+ particle-cli@1.29.0
updated 6 packages in 17.382s

>particle
 !   Error in particle-cli:
 !   Cannot find module 'babel-polyfill'
 !   See C:\Users\avazquezb\AppData\Local\particle\error.log for more info.

>npm install -g babel-polyfill
+ babel-polyfill@6.26.0
added 5 packages from 2 contributors in 4.653s

>particle
 !   Error in particle-cli:
 !   Cannot find module 'babel-polyfill'
 !   See C:\Users\avazquezb\AppData\Local\particle\error.log for more info.
```

Error log:
```
2018/05/22 13:34:41 Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\avazquezb\AppData\Local\particle\node_modules\particle-cli\bin\particle.js:4:1)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
2018/05/22 15:34:41 Time since last update 1h45m51.084265s, update in background
```

**Comment by monkbroc** [comment]
> EPERM: operation not permitted

Looks like something got messed up with the file permissions in the npm directory. I'm not sure how to fix this for your system. Maybe run `npm uninstall -g particle-cli`, then completely delete `C:\Users\avazquezb\AppData\Roaming\npm` and start from scratch?

I'd also recommend using the Windows CLI installer instead of npm install on Windows. https://docs.particle.io/guide/tools-and-features/cli/photon/#using-windows

**Comment by antoniovazquezblanco** [comment]
Uninstalled everything, removed every folder. After using the Windows CLI installer got it working again. Thanks
