### ISSUE TITLE
v1.43.2 breaks Tinker update

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/particle-cli#501]
I just tested with 1.43.1 which worked and immediately after updated to 1.43.2 which gave me this
```
C:\Users\andyr>particle --version
1.43.2

C:\Users\andyr>particle flash --usb tinker -v
dfu-util 0.8

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2014 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org

No such file or directory: Could not open file undefined for reading
Error writing firmware: No such file or directory: Could not open file undefined for reading

VError: Error writing firmware: No such file or directory: Could not open file undefined for reading

    at Promise.resolve.then.then.then.then.then.then.catch.err (C:\Users\andyr\AppData\Local\particle\node_modules\particle-cli\dist\cmd\flash.js:212:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
caused by: Error: No such file or directory: Could not open file undefined for reading

    at ensureError (C:\Users\andyr\AppData\Local\particle\node_modules\particle-cli\dist\lib\utilities.js:670:14)
    at Promise.resolve.then.then.then.then.then.then.catch.err (C:\Users\andyr\AppData\Local\particle\node_modules\particle-cli\dist\cmd\flash.js:212:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by technobly** [comment]
Thanks @ScruffR we'll get this fixed!
