### ISSUE TITLE
`particle-usb` dependency is missing or invalid

### ISSUE THREAD

**Issue by N-Coder** [particle-iot/particle-cli#525]
## Description

After an automatic update, probably due to the changes made in 1.44.0, none of the `usb` commands work anymore.
```
pi@raspberrypi:~/.particle $ particle usb list -v
! The `particle-usb` dependency is missing or invalid.
! Please reinstall: https://docs.particle.io/tutorials/developer-tools/cli/#installing
Cannot find module 'usb'
Error: Cannot find module 'usb'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/.particle/node_modules/particle-cli/node_modules/particle-usb/lib/usb-device-node.js:26:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```
I already tried deleting the `.particle` directory and running the installer again to no avail. There is nothing suspicious in error.log.

### Environment

* OS: Linux raspberrypi 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux (Raspberry Pi 3B+)
* Particle CLI: 1.47.0, installed using the installer (i.e. no system node/npm available)

**Comment by busticated** [comment]
ah, sorry about that. RasPi isn't an _officially_ supported platform but i'm just now discovering that we mention it in our docs 😬 

my hunch is that the `usb` module doesn't have prebuilt binaries for the platform. assuming you are able to run basic commands - e.g. `particle whoami` - here's what you can try:

1. install the required build tooling as described [here](https://github.com/tessel/node-usb#installation) (but don't try to run `npm i`)
2. `rm -rf ~/.particle/node_modules`
3. `particle update-cli`

at that point you should see `particle: Installing plugins...`, eventually the install should complete successfully, and you can re-try usb commands like `particle usb list`.

hope it helps!

**Comment by N-Coder** [comment]
That fixed it, thanks a lot! Now the particle-cli is fully functional again on the Raspberry Pi.
Seems like `udev` was either outdated or `libudev-dev` was missing.
Would that be something that should be handled automatically (or at least reported) by the installer?
```
pi@raspberrypi:~$ dpkg -l build-essential libudev-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                  Version                         Architecture                    Description
+++-=====================================================-===============================-===============================-================================================================================================================
ii  build-essential                                       12.3                            armhf                           Informational list of build-essential packages
dpkg-query: no packages found matching libudev-dev

pi@raspberrypi:~$ sudo apt-get install libudev-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libudev1 udev
The following NEW packages will be installed:
  libudev-dev
The following packages will be upgraded:
  libudev1 udev
2 upgraded, 1 newly installed, 0 to remove and 34 not upgraded.
Need to get 1286 kB of archives.
After this operation, 184 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://debian.bio.lmu.de/raspbian/raspbian stretch/main armhf udev armhf 232-25+deb9u12 [1072 kB]
Get:2 http://debian.bio.lmu.de/raspbian/raspbian stretch/main armhf libudev1 armhf 232-25+deb9u12 [121 kB]
Get:3 http://debian.bio.lmu.de/raspbian/raspbian stretch/main armhf libudev-dev armhf 232-25+deb9u12 [92.5 kB]
Fetched 1286 kB in 1s (969 kB/s)     
Reading changelogs... Done
(Reading database ... 62928 files and directories currently installed.)
Preparing to unpack .../udev_232-25+deb9u12_armhf.deb ...
Unpacking udev (232-25+deb9u12) over (232-25+deb9u11) ...
Preparing to unpack .../libudev1_232-25+deb9u12_armhf.deb ...
Unpacking libudev1:armhf (232-25+deb9u12) over (232-25+deb9u11) ...
Setting up libudev1:armhf (232-25+deb9u12) ...
Selecting previously unselected package libudev-dev:armhf.
(Reading database ... 62928 files and directories currently installed.)
Preparing to unpack .../libudev-dev_232-25+deb9u12_armhf.deb ...
Unpacking libudev-dev:armhf (232-25+deb9u12) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up udev (232-25+deb9u12) ...
addgroup: The group `input' already exists as a system group. Exiting.
update-initramfs: deferring update (trigger activated)
Processing triggers for systemd (232-25+deb9u11) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libudev-dev:armhf (232-25+deb9u12) ...
Processing triggers for initramfs-tools (0.130) ...
```

**Comment by busticated** [comment]
> That fixed it, thanks a lot!

ah, nice. glad that worked out :+1:

> Would that be something that should be handled automatically (or at least reported) by the installer?

if / when we start officially supporting RasPI, `particle-cli` will include prebuilt binaries for the `usb` dependency 👍
