### ISSUE TITLE
particle-cli DFU javascript error

### ISSUE THREAD

**Issue by markterrill** [particle-iot/particle-cli#540]
I highlighted this bug in another thread but a fortnight later no response. [update: seems to have been quietly fixed!]

## Description

Javascript error because you let the intern commit code.

### Steps to reproduce

May be hard to reproduce how I triggered it, trying to particle update a corrupted P1. Anyone coding for more than 3 months can see the issue.

### Expected result

No javascript error

### Actual result

Error:
```
Marks-2017MBP:particle-cli markterrill$ particle update
/Users/markterrill/.nvm/versions/node/v10.16.0/lib/node_modules/particle-cli/dist/lib/utilities.js:217
      defer.reject(msg);
            ^

TypeError: defer.reject is not a function
    at Timeout.setTimeout [as _onTimeout] (/Users/markterrill/.nvm/versions/node/v10.16.0/lib/node_modules/particle-cli/dist/lib/utilities.js:217:13)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

### Environment
Node 8.11
Latest particle CLI

### Discussion

Intern sent the wrong parameter to a nonsense function.
https://github.com/particle-iot/particle-cli/issues/498#issuecomment-560182448

### Bonus points
Who committed it?

**Comment by markterrill** [comment]
Found it's addressed: https://github.com/particle-iot/particle-cli/commit/9181c9b3e0f503452d36d0437887e381ea669cff#diff-849dd54296910cf2d9b12057cb8c8700
