### ISSUE TITLE
`particle login` says the `particle-usb` dependency is missing or invalid.

### ISSUE THREAD

**Issue by bblanchon** [particle-iot/particle-cli#716]
## Description

On a fresh GitHub runner, I installed Particle CLI, [as shown in the documentation](https://docs.particle.io/getting-started/developer-tools/cli/#advanced-install).
When I run `particle login`, I get the following error:

> The `particle-usb` dependency is missing or invalid.

### Steps to reproduce

1. `sudo npm install -g particle-cli`
2. `particle login -t "***"`

### Expected result

```text
Successfully completed login!
```

### Actual result

```text
! The `particle-usb` dependency is missing or invalid.
! Please reinstall: https://docs.particle.io/tutorials/developer-tools/cli/#installing
/usr/local/lib/node_modules/particle-cli/src/lib/require-optional.js:10
		throw error;
		^

Error: Cannot find module 'particle-usb'
Require stack:
- /usr/local/lib/node_modules/particle-cli/src/lib/require-optional.js
- /usr/local/lib/node_modules/particle-cli/src/lib/utilities.js
- /usr/local/lib/node_modules/particle-cli/src/cli/cloud.js
- /usr/local/lib/node_modules/particle-cli/src/cli/index.js
- /usr/local/lib/node_modules/particle-cli/src/app/cli.js
- /usr/local/lib/node_modules/particle-cli/src/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at module.exports (/usr/local/lib/node_modules/particle-cli/src/lib/require-optional.js:6:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/particle-cli/src/lib/utilities.js:39:69)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/particle-cli/src/lib/require-optional.js',
    '/usr/local/lib/node_modules/particle-cli/src/lib/utilities.js',
    '/usr/local/lib/node_modules/particle-cli/src/cli/cloud.js',
    '/usr/local/lib/node_modules/particle-cli/src/cli/index.js',
    '/usr/local/lib/node_modules/particle-cli/src/app/cli.js',
    '/usr/local/lib/node_modules/particle-cli/src/index.js'
  ]
}
```

### Environment

Tell us about your setup:

* OS: Ubuntu 22.04.3
* Node: 18.19.0
* Particle CLI: 3.21.0

**Comment by bblanchon** [comment]
This seems to be fixed now.
